name: Achievements
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename:  metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: asyrjasalo
          template: classic
          base: ""
          config_timezone: Europe/Helsinki
          plugin_achievements: yes
          plugin_achievements_display: compact
